#
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the sfss_zones module
"""
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


class ZonesArgs(object):  # pylint: disable=R0903
    """The arg spec for the sfss_zones module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'group_name': {'required': True, 'type': 'str'},
                                            'instance_id': {'required': True, 'type': 'int'},
                                            'members': {'type': 'dict',
                                                        'options': {'data': {'elements': 'dict',
                                                                             'options': {'id': {'required': True,
                                                                                                'type': 'str'},
                                                                                         'role': {'choices': ['host',
                                                                                                              'subsystem'],
                                                                                                  'type': 'str'},
                                                                                         'id_type': {'choices': ['nqn', 'zone_alias',
                                                                                                                 'fqn'],
                                                                                                     'default': 'nqn',
                                                                                                     'type': 'str'}},
                                                                             'type': 'list'}}},
                                            'name': {'required': True, 'type': 'str'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
