name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["type/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create this bug report. To better help us investigate this bug, please provide the information below.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: component
    attributes:
    label: Componenet or module Name
    description: What is the Component or Module Name?.
    placeholder:
        sfss_endpoints
    validations:
      required: true
  - type: input
    id: ansible
    attributes:
    label: Ansible Version
    description: Which Ansible Version being used?.
    placeholder:
        Ansible 2.12
    validations:
      required: true
  - type: input
    id: python
    attributes:
    label: Python Version
    description: Which Python Version being used?.
    placeholder:
        Python 3.8
        Python 3.9
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system is being used? Please provide the version as well.
      placeholder:
        Red Hat Enterprise Linux (RHEL) 8.5 and 8.4
        SUSE Linux Enterprise Server (SLES) 15 SP2 and 15 SP1
        Ubuntu 20.04.2 and 20.04.1
    validations:
      required: true
  - type: textarea
    id: playbook
    attributes:
    label: Playbook Used
    description: What is the playbook used to run?
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Logs
      description: Copy/paste any relevant log output here or Upload log files by dragging and dropping the files into the text area. Please be sure to remove all sensitive data such as IP addresses, host names, credentials, etc.
    validations:
      required: true    
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can taken to reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload any relevant screenshots here by dragging and dropping the files into the text area.
    validations:
      required: false  
  - type: input
    id: ainfo
    attributes:
      label: Additional Information
      description: Provide any additional information.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Community Note
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) 
          to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, 
          they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
