---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc.sfss
  tasks:
    - name: "Gather facts"
      sfss_facts:
        gather_network_resources: all
      register: result
