---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc.sfss
  tasks:
    - name: "Gather facts"
      sfss_facts:
        gather_subset: min
        gather_network_resources: 
          - interface_ip_mgmt
      register: result
    - name: Sfss ip interface create
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.1.1.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51

    - name: SFSS Ip interface delete
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.1.1.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51
        state: deleted