---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc.sfss
  tasks:
    - name: "Gather facts"
      sfss_facts:
        gather_subset: min
        gather_network_resources: 
          - interface_ip_mgmt
      register: result

    - name: Sfss ip interface edit ethernet interface
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 1.1.1.1
          ipv4_config_type: manual
          ipv4_gateway: 0.0.0.0
          ipv4_netmask: 32
          ipv6_config_type: automatic
          parent_interface: ens192
    - name: Sfss ip vlan interface create with disabled config type
      sfss_interface_ip_mgmt:
        config:
        - ipv4_config_type: disabled
          ipv6_config_type: disabled
          parent_interface: ens192
          vlan_id: 51
          name: vlan interface
    - name: Sfss ip vlan interface create with interface name
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.2.2.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51
          name: vlan interface

    - name: Sfss ip vlan interface edit name
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.2.2.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51
          name: vlan interface edited
    
    - name: Sfss ip vlan interface delete name
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.2.2.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51

    - name: SFSS Ip interface delete
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 52.1.1.2
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv6_address: fe52::1699:6f09:43dd:56c2
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f09:43dd:ffff
          ipv6_netmask: 64
          parent_interface: ens192
          vlan_id: 51
        state: deleted

    - name: Sfss ip vlan interface create with routes
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 10.10.10.10
          ipv4_config_type: manual
          ipv4_gateway: 10.1.1.254
          ipv4_netmask: 16
          ipv4_routes:
          - destination: 3.3.3.3
            destination_prefix: 16
            next_hop: 5.5.5.5
            metric: 32
          - destination: 1.1.1.1
            destination_prefix: 16
            next_hop: 6.6.6.6
            metric: 25
          ipv6_address: fe52::1699:6f07:43df:56c3
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f07:43df:ffff
          ipv6_netmask: 64
          ipv6_routes:
          - destination: 1::2
            destination_prefix: 16
            next_hop: 3::3
            metric: 32
          parent_interface: ens225
          vlan_id: 51
          name: vlan interface

    - name: Sfss ip vlan interface edit the created routes
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 10.10.10.10
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv4_routes:
          - destination: 3.3.4.5
            destination_prefix: 16
            next_hop: 5.5.5.6
          - destination: 1.1.1.1
            destination_prefix: 16
            next_hop: 6.6.6.6
          ipv6_address: fe52::1699:6f07:43df:56c3
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f07:43df:ffff
          ipv6_netmask: 64
          ipv6_routes:
          - destination: 1::2
            destination_prefix: 16
            next_hop: 3::3
            metric: 32
          parent_interface: ens225
          vlan_id: 51
          name: vlan interface

    - name: Sfss ip vlan interface delete the created routes
      sfss_interface_ip_mgmt:
        config:
        - ipv4_address: 10.10.10.10
          ipv4_config_type: manual
          ipv4_gateway: 52.1.1.254
          ipv4_netmask: 16
          ipv4_routes:
          ipv6_address: fe52::1699:6f07:43df:56c3
          ipv6_config_type: manual
          ipv6_gateway: fe52::1699:6f07:43df:ffff
          ipv6_netmask: 64
          ipv6_routes:
          parent_interface: ens225
          vlan_id: 51
          name: vlan interface
    
    - name: SFSS Ip interface delete all vlan interfaces
      sfss_interface_ip_mgmt:
        config: []
        state: deleted