---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc.sfss
  tasks:
    - name: "Gather facts"
      sfss_facts:
        gather_subset: min
        gather_network_resources: 
          - zone_alias
      register: result
    - name: SFSS zones alias create
      sfss_zone_alias:
        config:
        - name: Ansible123
          instance_id: 1
          members:
            data: 
              - id: "nqn.2014-08.org.nvmexpress:uuid:0000:host"
                type: 'nqn'
                role: 'subsystem'
              - id: "nqn.2014-08.org.nvmexpress:uuid:0001:host"
                type: 'nqn'
                role: 'subsystem'
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@2.2.2.2:V4::0:0:TCP"
                type: 'fqn'
                role: 'subsystem'
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@2.2.2.1:V4::0:0:TCP"
                type: 'fqn'
                role: 'host'
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@2.2.2.3:V4::0:0:TCP"
                type: 'fqn'
                role: 'host'
              - id: "nqn1.2014-08.org.nvmexpress:uuid:host@2.2.2.2:V4::0:0:TCP"
                type: 'fqn'
                role: 'host'                
    - name: SFSS zones alias delete
      sfss_zone_alias:
        config:
        - name: Ansible123
          instance_id: 1
          members:
            data: 
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@2.2.2.2:V4::0:0:TCP"
                type: 'nqn'
                role: 'subsystem'
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@3.3.3.3:V4::0:0:TCP"
                type: 'nqn'
                role: 'subsystem'
              - id: "nqn.2014-08.org.nvmexpress:uuid:host@4.4.4.4:V4::0:0:TCP"
                type: 'fqn'
                role: 'subsystem'
        state: deleted