---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  tasks:
    - name: SFSS zones create
      dellemc.sfss.sfss_zones:
        config:
          - name: reg.zone1
            instance_id: 1
            group_name: reg.zone_group1
            members:
              data:
                - id: nqn.2014-08.org.nvmexpress:uuid:00000000-0000-1111-0002-00000000000@2.2.2.2:V4::0:0:TCP
                  id_type: fqn
                  role: host
                - id: nqn.2014-08.org.nvmexpress:uuid:00000000-0000-1111-0002-00000000000
                  id_type: nqn
                  role: subsystem
    
    - name: SFSS zones delete
      dellemc.sfss.sfss_zones:
        config:
          - name: reg.zone1
            instance_id: 1
            group_name: reg.zone_group1
            members:
              data:
                - id: nqn.2014-08.org.nvmexpress:uuid:00000000-0000-1111-0002-00000000000@2.2.2.2:V4::0:0:TCP
                  id_type: fqn
                  role: host
        state: deleted