#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfss_interface_ip_mgmt
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


DOCUMENTATION = """
---
module: sfss_interface_ip_mgmt
version_added: 1.0.0
notes:
- Idempotent is supported.
- Supports C(check_mode).
short_description: Manage SFSS APP interfaces
description:
  - This module is used to manage SFSS application interfaces. This module is used to create subinterfaces and assign IP address to the subinterfaces.
author: Mohamed Javeed (@javeedf)
options:
  config:
    description: A list of interfaces.
    type: list
    elements: dict
    suboptions:
      vlan_id:
        description:
          - VLAN ID for creating the subinterface.
        type: int
      parent_interface:
        description:
          - Parent interface name to create the subinterface based on the VLAN ID.
        type: str
        required: True
      ipv4_address:
        description:
          - IPv4 address of the subinterface.
        type: str
      ipv4_netmask:
        description:
          - Subnet mask of the subinterface IPv4 address.
        type: int
      ipv4_gateway:
        description:
          - IPv4 Gateway address of the subinterface.
        type: str
      ipv4_config_type:
        description:
          - Configuration type.
        type: str
        required: True
        choices:
        - manual
        - automatic
      ipv6_address:
        description:
          - IPv6 address of the subinterface.
        type: str
      ipv6_netmask:
        description:
          - Subnet mask of the subinterface IPv6 address.
        type: int
      ipv6_gateway:
        description:
          - IPv6 Gateway address of the subinterface.
        type: str
      ipv6_config_type:
        description:
          - Configuration type.
        type: str
        required: True
        choices:
        - manual
        - automatic
  state:
    description:
      - The state the configuration should be left in.
    type: str
    choices:
     - merged
     - deleted
    default: merged
"""
EXAMPLES = """
# Using deleted
#
# Before state:
# -------------
#
# redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# "IpAddressManagements": [
# {
#   "Interface": "ens192.51",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "52.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "52.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe52::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe52::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 51,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.51')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.76",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "76.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "76.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe76::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe76::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 76,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.76')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.77",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "77.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "77.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe77::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe77::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 77,
#   "ParentInterface": "ens192",
#   "VlanId": 77,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.77')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.74",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "74.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "74.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe74::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe74::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 74,
#   "ParentInterface": "ens192",
#   "VlanId": 74,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.74')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.64",
#   "Type": "VLAN",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "ParentInterface": "ens192",
#   "VlanId": 64,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.64')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192",
#   "Type": "ETHERNET",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens160",
#   "Type": "ETHERNET",
#   "IPV4Address": [
#       "100.104.26.127"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "100.104.26.254",
#   "IPV4PrefixLength": 24,
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens160')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.75",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "75.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "75.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe75::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe75::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 75,
#   "ParentInterface": "ens192",
#   "VlanId": 75,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.75')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# }
# ]
- name: Stfs interface ip management
  dellemc.sfss.interface_ip_mgmt:
    config:
    - ipv4_address: 52.1.1.2
      ipv4_config_type: manual
      ipv4_gateway: 52.1.1.254
      ipv4_netmask: 16
      ipv6_address: fe52::1699:6f09:43dd:56c2
      ipv6_config_type: manual
      ipv6_gateway: fe52::1699:6f09:43dd:ffff
      ipv6_netmask: 64
      parent_interface: ens192
      vlan_id: 51
    state: deleted
#
# After state:
# -------------
#
# redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# "IpAddressManagements": [
# {
#   "Interface": "ens192.76",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "76.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "76.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe76::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe76::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 76,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.76')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.77",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "77.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "77.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe77::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe77::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 77,
#   "ParentInterface": "ens192",
#   "VlanId": 77,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.77')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.74",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "74.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "74.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe74::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe74::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 74,
#   "ParentInterface": "ens192",
#   "VlanId": 74,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.74')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.64",
#   "Type": "VLAN",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "ParentInterface": "ens192",
#   "VlanId": 64,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.64')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192",
#   "Type": "ETHERNET",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens160",
#   "Type": "ETHERNET",
#   "IPV4Address": [
#       "100.104.26.127"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "100.104.26.254",
#   "IPV4PrefixLength": 24,
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens160')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.75",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "75.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "75.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe75::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe75::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 75,
#   "ParentInterface": "ens192",
#   "VlanId": 75,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.75')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# }
# ]
#
#
# Using deleted
#
# Before state:
# -------------
#redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# "IpAddressManagements": [
# {
#   "Interface": "ens192.51",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "52.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "52.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe52::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe52::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 51,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.51')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.76",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "76.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "76.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe76::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe76::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 76,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.76')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.77",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "77.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "77.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe77::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe77::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 77,
#   "ParentInterface": "ens192",
#   "VlanId": 77,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.77')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.74",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "74.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "74.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe74::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe74::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 74,
#   "ParentInterface": "ens192",
#   "VlanId": 74,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.74')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.64",
#   "Type": "VLAN",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "ParentInterface": "ens192",
#   "VlanId": 64,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.64')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192",
#   "Type": "ETHERNET",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens160",
#   "Type": "ETHERNET",
#   "IPV4Address": [
#       "100.104.26.127"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "100.104.26.254",
#   "IPV4PrefixLength": 24,
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens160')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.75",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "75.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "75.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe75::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe75::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 75,
#   "ParentInterface": "ens192",
#   "VlanId": 75,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.75')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# }
# ]
- name: Stfs interface ip management
  dellemc.sfss.interface_ip_mgmt:
    config: []
    state: deleted
#
# After state:
# ------------
# redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# {
# "IpAddressManagements@odata.count": 0,
# "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements",
# "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements",
# "@odata.type": "#IpAddressManagementsCollection.IpAddressManagementsCollection"
# }
#
# Using merged
#
# Before state:
# -------------
#
# redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# "IpAddressManagements": [
# {
#   "Interface": "ens192.76",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "76.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "76.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe76::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe76::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 76,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.76')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.77",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "77.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "77.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe77::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe77::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 77,
#   "ParentInterface": "ens192",
#   "VlanId": 77,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.77')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.74",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "74.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "74.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe74::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe74::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 74,
#   "ParentInterface": "ens192",
#   "VlanId": 74,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.74')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.64",
#   "Type": "VLAN",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "ParentInterface": "ens192",
#   "VlanId": 64,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.64')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192",
#   "Type": "ETHERNET",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens160",
#   "Type": "ETHERNET",
#   "IPV4Address": [
#       "100.104.26.127"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "100.104.26.254",
#   "IPV4PrefixLength": 24,
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens160')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.75",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "75.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "75.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe75::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe75::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 75,
#   "ParentInterface": "ens192",
#   "VlanId": 75,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.75')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# }
# ]
- name: Stfs interface ip management
  dellemc.sfss.interface_ip_mgmt:
    config:
    - ipv4_address: 52.1.1.2
      ipv4_config_type: manual
      ipv4_gateway: 52.1.1.254
      ipv4_netmask: 16
      ipv6_address: fe52::1699:6f09:43dd:56c2
      ipv6_config_type: manual
      ipv6_gateway: fe52::1699:6f09:43dd:ffff
      ipv6_netmask: 64
      parent_interface: ens192
      vlan_id: 51
#
# After state:
# -------------
#
# redfish/v1/SFSSApp/IpAddressManagements?$expand=IpAddressManagements
# "IpAddressManagements": [
# {
#   "Interface": "ens192.51",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "52.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "52.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe52::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe52::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 51,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.51')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.76",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "76.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "76.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe76::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe76::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 64,
#   "ParentInterface": "ens192",
#   "VlanId": 76,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.76')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.77",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "77.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "77.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe77::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe77::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 77,
#   "ParentInterface": "ens192",
#   "VlanId": 77,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.77')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.74",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "74.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "74.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe74::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe74::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 74,
#   "ParentInterface": "ens192",
#   "VlanId": 74,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.74')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.64",
#   "Type": "VLAN",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "ParentInterface": "ens192",
#   "VlanId": 64,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.64')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192",
#   "Type": "ETHERNET",
#   "IPV4Config": "AUTOMATIC",
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens160",
#   "Type": "ETHERNET",
#   "IPV4Address": [
#       "100.104.26.127"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "100.104.26.254",
#   "IPV4PrefixLength": 24,
#   "IPV6Config": "AUTOMATIC",
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens160')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# },
# {
#   "Interface": "ens192.75",
#   "Type": "VLAN",
#   "IPV4Address": [
#       "75.1.1.2"
#   ],
#   "IPV4Config": "MANUAL",
#   "IPV4Gateway": "75.1.1.254",
#   "IPV4PrefixLength": 16,
#   "IPV6Address": [
#       "fe75::1699:6f09:43dd:56c2"
#   ],
#   "IPV6Config": "MANUAL",
#   "IPV6Gateway": "fe75::1699:6f09:43dd:ffff",
#   "IPV6PrefixLength": 75,
#   "ParentInterface": "ens192",
#   "VlanId": 75,
#   "@odata.id": "/redfish/v1/SFSSApp/IpAddressManagements('ens192.75')",
#   "@odata.type": "#IpAddressManagements.IpAddressManagements",
#   "@odata.context": "/redfish/v1/SFSSApp/$metadata#IpAddressManagements/IpAddressManagements/$entity"
# }
# ]
"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
  type: list
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
  type: list
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sfss.plugins.module_utils.network.sfss.argspec.interface_ip_mgmt.interface_ip_mgmt import Interface_ip_mgmtArgs
from ansible_collections.dellemc.sfss.plugins.module_utils.network.sfss.config.interface_ip_mgmt.interface_ip_mgmt import Interface_ip_mgmt


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Interface_ip_mgmtArgs.argument_spec,
                           supports_check_mode=True)

    result = Interface_ip_mgmt(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
